### ISSUE TITLE
Update Databricks RAPIDS integration example

### ISSUE THREAD

**Issue by sauravdev** [rapidsai/cloud-ml-examples#109]
https://github.com/rapidsai/cloud-ml-examples/blob/main/databricks/README.md Looks to be outdated as it is for DataBricks ML Runtime 6.6 which is not supported now, can we please update the init script for latest RAPIDS and Databricks Runtime version?

**Comment by zronaghi** [comment]
Thanks @sauravdev for reporting, we're in the process of updating the instructions to use containers

**Comment by zronaghi** [comment]
This [PR ](https://github.com/databricks/containers/pull/53 ) will update Databricks containers with CUDA 11 and RAPIDS 0.19

**Comment by zronaghi** [comment]
I was able to build a GPU conda image with CUA 11 (zronaghi/rapidsai:databricks-conda), using Databrick's Dockerfiles and start up a cluster on Azure. But all notebook commands get canceled. @drobison00 can you also look into it?

**Comment by zronaghi** [comment]
Here's the latest: DB recently updated containers with CUDA 11. After looking at the logs and GH, need to set the default conda env in the Dockerfile and couple of packages (ipython and ipykernel) are required for Python notebooks. I was able to access the GPUs and run a few commands with https://github.com/rapidsai/cloud-ml-examples/pull/120, working on adding RAPIDS libs.
