### ISSUE TITLE
Update all examples with RAPIDS 21.06

### ISSUE THREAD

**Issue by zronaghi** [rapidsai/cloud-ml-examples#126]

**Comment by zronaghi** [comment]
Can you all update the following examples and/or verify they work as expected:

@drobison00 GCP notebook using [packed conda](https://github.com/rapidsai/cloud-ml-examples/blob/main/gcp/notebook_setup/README.md), [HPO with container](https://github.com/rapidsai/cloud-ml-examples/blob/main/gcp/README.md#deploy-a-custom-rapids-training-container-utilizing-the-airline-dataset-and-initiate-a-training-job-with-support-for-hyperparameter-optimization-hpo) and GKE

@Nanthini10 SageMaker with [lifecycle script](https://github.com/rapidsai/cloud-ml-examples/blob/main/aws/environment_setup/lifecycle_script), Azure cloudprovider RF, Azure SHAP - I'll update HPO since I have to run through it today

@akaanirban Azure K8s and cloudprovider PR

@sarahyurick SageMaker HPO (HPO and extended notebooks), these both will pull the latest so now that 21.06 has been added will use that, just need to run through both to verify it works

**Comment by drobison00** [comment]
Required GCP updates: https://github.com/rapidsai/cloud-ml-examples/pull/134

**Comment by zronaghi** [comment]
These all have been updated!
