### ISSUE TITLE
[DOC] Update Examples to 22.08

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cloud-ml-examples#157]
Currently, cloud ml examples, except for Azure, point to RAPIDS 0.18, confusing some

- [ ]  Azure: dask-cloud provider
- [ ]  Azure: other examples
- [ ]  AWS
- [ ]  GCP
- [ ] Other cloud link outs

Combines and supercedes #154

Thanks @sophwats!
cc @mmccarty

**Comment by mmccarty** [comment]
Breakdown in [tracker](https://docs.google.com/spreadsheets/d/1K8z3HsYmpJovtb-SJDdtlZiZxmcLI5ghl7EGe0Z54U0/edit?usp=sharing)

**Comment by hcho3** [comment]
@mmccarty Can you assign me this issue?

**Comment by jarmak-nv** [comment]
@hcho3 @isVoid 

Had a chance to try these? If yes, any challenges with these?

@skirui-source 

I'm still working on getting you a Databricks acct.
