### ISSUE TITLE
Include `ucx-proc=*=gpu`

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cloud-ml-examples#163]
Looks like there are a few environment files specifying `ucx` & `ucx-py` here that don't also specify `ucx-proc`. While the very tight pinning likely enforces `ucx-proc=*=gpu` indirectly, it would be good to include it explicitly as well. This would also be helpful if the pinnings are relaxed in the future.

**Comment by mmccarty** [comment]
Thanks @jakirkham Any idea why we pin so tightly in these environment files? I'm considering loosening the pins.

**Comment by jakirkham** [comment]
Honestly I'm not too familiar with them. So couldn't say

It might make sense to have tighter pins if we are concerned about exact reproducibility. Though agree that loosening would be good (if that doesn't cause issues)
