### ISSUE TITLE
rapids-spec.txt for databricks container

### ISSUE THREAD

**Issue by alexHeu** [rapidsai/cloud-ml-examples#199]
Hi,

I am currently working with the rapids docker image for databricks but I would like to customize the rapids-spec.txt to include a few other libraries.
Is it possible to find the rapids-spec.txt, that is built within the container, in some other repository?

Thanks!

**Comment by alexHeu** [comment]
Thanks. I will try it that way

**Comment by jacobtomlinson** [comment]
Ok great. I'm going to close this out but feel free to comment back here is you need any more support.
