### ISSUE TITLE
Moving from `pynvml` to `nvidia-ml-py`

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cloud-ml-examples#242]
Currently this is making use of `pynvml` in a few places:

https://github.com/rapidsai/cloud-ml-examples/blob/5692c1655cd2581d696fdba0fb503d18097cddff/gcp/docker/infrastructure/rapids_lib.py#L29

https://github.com/rapidsai/cloud-ml-examples/blob/5692c1655cd2581d696fdba0fb503d18097cddff/gcp/docker/infrastructure/rapids_lib.py#L248-L251

https://github.com/rapidsai/cloud-ml-examples/blame/5692c1655cd2581d696fdba0fb503d18097cddff/gcp/notebooks/custom_hpo.ipynb#L81

https://github.com/rapidsai/cloud-ml-examples/blob/5692c1655cd2581d696fdba0fb503d18097cddff/azure/code/rapids_csp_azure.py#L38

However we would like to move to `nvidia-ml-py` in the future. Raising this issue to track this work

**Comment by jacobtomlinson** [comment]
Thanks John! This repo is in the process of being archived and content being migrated to `rapidsai/deployment` so I'm going to close this in favour of https://github.com/rapidsai/deployment/issues/151

**Comment by jakirkham** [comment]
Ah ok. Sorry for the noise then

There was a bit of gray area when looking through these repos to ascertain, which still needed attention
