### ISSUE TITLE
[FEA] Update the GCP Dockerfile.training file

### ISSUE THREAD

**Issue by Salonijain27** [rapidsai/cloud-ml-examples#31]
The current Dockerfile.training uses the 0.13 rapids nightly docker container
https://github.com/rapidsai/cloud-ml-examples/blob/d53bdba6bc72ba05e631e47411b826bdcdd1615c/gcp/docker/Dockerfile.training#L2
. As it is a nightly container, the one for version 0.13 it is not there anymore (https://hub.docker.com/r/rapidsai/rapidsai-nightly/tags)

It would be nice to have an option to choose the type of docker container to be used (nightly or stable)  and or the version number as well

**Comment by zronaghi** [comment]
This Dockerfile has been updated with the latest stable release, thanks!
