### ISSUE TITLE
Update HPO examples to pull unified container 

### ISSUE THREAD

**Issue by zronaghi** [rapidsai/cloud-ml-examples#58]
Let's update the SageMaker, AzureML and AI Platfrom notebooks to use [rapids-cloud-ml](https://hub.docker.com/r/rapidsai/rapidsai-cloud-ml) images for HPO

**Comment by drobison00** [comment]
@zronaghi AI platform is probably not compatible. Google wants you to build from their base notebooks there.

See: https://github.com/rapidsai/cloud-ml-examples/blob/main/gcp/docker/Dockerfile.jupyter_notebook
```dockerfile
FROM gcr.io/deeplearning-platform-release/base-cu110
```

**Comment by zronaghi** [comment]
Which example can we use this for then? https://github.com/rapidsai/cloud-ml-examples/blob/main/common/docker/Dockerfile.training.unified#L75

**Comment by drobison00** [comment]
That works for launching jobs directly on the AI platform; I'll add a PR that updates the examples to use the cloud-ml images shortly.

**Comment by miroenev** [comment]
There is an issue with the 0.17 cuda 11.0 unified container exceeding storage of the default docker volume in SageMaker during the pull (extraction stage). The unified 0.17 cuda 10.2 container seems to barely fit, should I go with that?

**Comment by zronaghi** [comment]
Would be good to add the PR with 11.0 and we can merge for SageMaker after reducing the size of the container
