### ISSUE TITLE
[FEA] Inference serving with K8s + Triton-FIL

### ISSUE THREAD

**Issue by zronaghi** [rapidsai/cloud-ml-examples#75]
Benchmarking on A100s

**Comment by hcho3** [comment]
It will be cool to set up Triton-FIL in k8s setting

**Comment by jacobtomlinson** [comment]
It looks like there are already some examples for this. They just need cleaning up and testing.

https://github.com/rapidsai/cloud-ml-examples/tree/main/triton/kubernetes

**Comment by hcho3** [comment]
Closing in favor of #240
