### ISSUE TITLE
Update all containers to 0.19

### ISSUE THREAD

**Issue by zronaghi** [rapidsai/cloud-ml-examples#90]
AWS, Azure, GCP in cloud-ml
SageMaker : https://github.com/aws/amazon-sagemaker-examples/tree/master/hyperparameter_tuning/rapids_bring_your_own
AzureML: https://github.com/Azure/azureml-examples/blob/main/tutorials/using-rapids/DOCKERFILE

**Comment by drobison00** [comment]
GCP Workflows all use the unified container, with the exception of the AI platform notebooks which still appear to only support RAPIDS 0.18 [EXPERIMENTAL].

PR for GCP does update some language and version defaults in example scripts.
https://github.com/rapidsai/cloud-ml-examples/pull/101
