### ISSUE TITLE
MNMG cuML + XGB on GCP - cloudprovider

### ISSUE THREAD

**Issue by zronaghi** [rapidsai/cloud-ml-examples#95]
Extending the dask-k8s examples to cloudproivder

**Comment by drobison00** [comment]
Depends on: https://github.com/dask/dask-cloudprovider/issues/281

**Comment by hcho3** [comment]
Update: I was able to set up a K8s cluster on Google Cloud, install KubeFlow with the Dask operator, and get Optuna to run a toy HPO job in parallel using the KubeCluster. See https://github.com/hcho3/xgb-hpo-k8s-notebooks/blob/main/barebones-hpo-kubecluster-dask.ipynb

**Comment by hcho3** [comment]
Update: I got parallel HPO working with XGBoost GPU: https://github.com/hcho3/xgb-hpo-k8s-notebooks/blob/main/barebones-hpo-kubecluster-dask.ipynb

**Comment by hcho3** [comment]
Completed in https://github.com/rapidsai/cloud-ml-examples/pull/192

**Comment by hcho3** [comment]
For the record, here is the command to launch a K8s cluster on GCP:
```
gcloud container clusters create rapids-gpu-kubeflow \
  --accelerator type=nvidia-tesla-p100,count=2 --machine-type n1-standard-4 \
  --zone us-central1-c --release-channel stable
```
