### ISSUE TITLE
MNMG XGBoost from SageMaker

### ISSUE THREAD

**Issue by zronaghi** [rapidsai/cloud-ml-examples#96]

**Comment by jacobtomlinson** [comment]
Replicate this notebook https://github.com/rapidsai/cloud-ml-examples/blob/main/gke-dask/notebooks/xgboost-gpu-hpo-job-parallel-k8s.ipynb but driven from Sagemaker

**Comment by skirui-source** [comment]
https://github.com/rapidsai/cloud-ml-examples/blob/main/k8s-dask/notebooks/xgboost-gpu-hpo-job-parallel-k8s.ipynb
